### ISSUE TITLE
Render default link as span

### ISSUE THREAD

**Issue by zyuhel** [Adamant-im/adamant-im#15]
May be it will be more secure, to render all incoming links as spans, and only on click (touch) on them convert to links, so if browsers will try to prefetch links automatically (what they shouldn't do) they won't be able to do it.

**Comment by chovy** [comment]
According to this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

prefetch only works on `<link>` tags not `<a href="#">`
