### ISSUE TITLE
HealthCheck should check height offset

### ISSUE THREAD

**Issue by zyuhel** [Adamant-im/adamant-im#175]
If one of available nodes is in re-sync state or stalled, it's height will greatly differ from live ones, so healthcheck should mark that nodes as offline ones, and doesn't use them when making queries.

We should use `/api/blocks/getHeight` endpoint. Possible height difference should be around 20-50 blocks.

**Comment by adamant-al** [comment]
Used /status endpoint, which returns node height as well as version.
