### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [Adamant-im/adamant-im#293]
**Objective**: Implement and Support i2p in Adamant
**Description**: Explore the possibility of using Adamant over i2p.
Would non-i2p users be able to still communicate? Would you need to craft a bridge?
**Why?**: Many reasons, mainly for privacy and security but also to support decentralized communications. 

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75488637-feature-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75488637)](https://www.bountysource.com/issues/75488637-feature-support-i2p)

**Comment by adamant-al** [comment]
We have no plans to support i2p now.
However, Tor app is available: http://adamantmsg72ixni.onion
