### ISSUE TITLE
Sometimes new message notification doesn't clear

### ISSUE THREAD

**Issue by zyuhel** [Adamant-im/adamant-im#39]
Sometimes new message title bar notification doesn't remove even after message has been read.
It seems that browser had ignored title update, or has updated it in incorrect order.

**Comment by adamant-al** [comment]
Sample [img]https://i.imgur.com/QQoN6bN.png[/img]

**Comment by adamant-al** [comment]
https://github.com/Adamant-im/adamant-im/commit/100e6147192bdab5ca1f6a3ff5c31fed1270f858
