### ISSUE TITLE
Notification when switching browser tab do not work

### ISSUE THREAD

**Issue by adamant-al** [Adamant-im/adamant-im#53]
When receiving new message and screen with chat is opened, no sound of new message.
This is fine when you are in this browser tab. But if you switched a tab to another, need for notification sound as well as Title notification.

**Comment by chovy** [comment]
Do we have an audio file we can use?

**Comment by adamant-al** [comment]
https://github.com/Adamant-im/adamant-im/commit/100e6147192bdab5ca1f6a3ff5c31fed1270f858
